name: GitHub Actions Demo
on: 
  workflow_dispatch:
jobs:
  Check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python --version 
  test-with-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install pylint flask
      - run: pylint app.py
